# Generated by Django 2.0.13 on 2019-08-01 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductType',
            new_name='Vehicle',
        ),
    ]
