# Generated by Django 2.0.13 on 2019-08-01 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20190731_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DPI', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=60)),
                ('NIT', models.CharField(max_length=20)),
                ('Direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.Cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
