# Generated by Django 2.0.13 on 2019-08-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20190731_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
