# Generated by Django 2.0.13 on 2019-08-01 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_vehiculo_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='name',
            new_name='nombre',
        ),
    ]
